In [3]:
import pandas as pd
import glob
import datetime as dt
import networkx as nx
import operator
import random

In [4]:
def loadEdgelist(filename):
	# Readin graph
	g = nx.read_edgelist(filename, 
	                     delimiter="\t", 
	                     create_using  = nx.DiGraph(), 
	                     data=True)

	# Convert Weight To Float
	temp = map(lambda (x, y): (x, float(y)), 
			   nx.get_edge_attributes(g, "weight").items())
	nx.set_edge_attributes(g, "weight", dict(temp))

	# Convert Date to datetime
	temp = map(lambda (x, y): (x, dt.datetime.strptime(y, "%Y-%m-%d")), 
			   nx.get_edge_attributes(g, "date").items())
	nx.set_edge_attributes(g, "date", dict(temp))

	return g

def writeEdgelist(g, filename):
    # Convert date to string
    temp = map(lambda (x, y): (x, y.strftime('%Y-%m-%d')), 
               nx.get_edge_attributes(g, "date").items())
    nx.set_edge_attributes(g, "date", dict(temp))
    
    
    # Write to file
    nx.write_edgelist(g,filename, delimiter="\t", data=True)


In [68]:
preG = loadEdgelist("../1_snapshotting/cumulative_snapshots/enddate_20140228.edgelist")
# Set node attributes. 0 is an investor, 1 is a company.
node_attributes =dict(map(lambda (x,y): (x,1) if y > 0 else (x,0), 
                      preG.in_degree().items()))
nx.set_node_attributes(preG, "bipartite", node_attributes)

In [157]:
def predict(company, new_edges, investors):
    predict = [random.choice(investors) for i in range(0, len(new_edges))]
    return sum(map(lambda x: 1 if x in new_edges else 0, predict))


investors = dict(investor_degree).keys()
i = 0
total_correct = 0
for company in new_edges_s.keys():
    total_correct += predict(company, new_edges_s[company], investors)
    i += 1
    if i % 1000 == 0:
        print i

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000


In [6]:
postG = loadEdgelist("../1_snapshotting/cumulative_snapshots/enddate_20150831.edgelist")

In [67]:
preG.out_degree().items()

[(u'/organization/rsj-private-equity', 2),
 (u'/organization/petra-partners', 1),
 (u'/organization/kaymu', 0),
 (u'/person/emilios-markou', 1),
 (u'/person/dave-leyrer', 1),
 (u'/organization/basicgov-systems', 0),
 (u'/organization/beamonte-investments', 2),
 (u'/organization/inventures', 2),
 (u'/organization/healthbox', 47),
 (u'/organization/forticom', 2),
 (u'/organization/jooce', 0),
 (u'/person/erik-rannala', 1),
 (u'/person/patric-svanberg', 1),
 (u'/organization/standoutjobs', 0),
 (u'/organization/svb-india-capital-partners', 2),
 (u'/organization/fjme-ventures', 1),
 (u'/organization/opencare', 0),
 (u'/organization/afisha-rambler', 1),
 (u'/organization/cape-wind', 0),
 (u'/person/anand-lunia', 2),
 (u'/organization/access2net', 1),
 (u'/organization/han-grass-biomass', 0),
 (u'/person/b7inc-peter-thorp', 1),
 (u'/organization/avuba', 0),
 (u'/organization/teleflip', 0),
 (u'/organization/seek-adore', 0),
 (u'/person/jamie-curtis', 1),
 (u'/organization/solidcore-systems',

In [8]:
investors = preG.out_degree(weight = "weight").items()

In [69]:
companies_weights = filter(lambda (x,y): y != 0, preG.in_degree(weight = "weight").items())
companies_edges = preG.in_degree()
companies_joined = {}
for c in companies_weights:
    c_key = c[0]
    weights = c[1]
    num_edges = companies_edges[c_key]
    companies_joined[c_key] = (num_edges,weights)
    
    

In [70]:
companies_joined['/organization/uber']

(29, 209213253.0)

In [71]:
investors_weights = filter(lambda (x,y): y != 0, preG.out_degree(weight = "weight").items())
investors_edges = preG.out_degree()
investors_joined = {}
for i in investors_weights:
    i_key = i[0]
    weights = i[1]
    num_edges = investors_edges[i_key]
    investors_joined[i_key] = (num_edges,weights)
    
    

In [72]:
investors_joined

{u'/organization/rsj-private-equity': (2, 483333.0),
 u'/organization/petra-partners': (1, 10000000.0),
 u'/organization/ivycap-ventures': (3, 1800000.0),
 u'/organization/abacus-capital-group': (1, 1700000.0),
 u'/organization/flora-family-foundation': (1, 80000.0),
 u'/person/ali-partovi': (19, 14693713.0),
 u'/person/emilios-markou': (1, 47604.0),
 u'/person/dave-leyrer': (1, 160714.0),
 u'/person/jack-herrick': (3, 3065909.0),
 u'/organization/technology-venture-investors': (3, 9200000.0),
 u'/person/peter-steinberg': (1, 54000.0),
 u'/organization/beamonte-investments': (2, 240000.0),
 u'/person/jayan-ramankutty': (1, 360000.0),
 u'/organization/inventures': (2, 1166666.0),
 u'/organization/healthbox': (47, 465864.0),
 u'/organization/investment-and-venture-fund-of-the-republic-of-tatarstan': (2,
  135000.0),
 u'/organization/forticom': (2, 55000000.0),
 u'/person/azat-mardanov': (1, 48571.0),
 u'/person/eddy-chan': (1, 133333.0),
 u'/person/erik-rannala': (1, 107142.0),
 u'/organ

In [73]:
companies_joined, investors_joined

({u'/organization/weplay': (7, 10567500.0),
  u'/organization/loop-commerce': (10, 6199993.0),
  u'/organization/dunwello': (10, 1400000.0),
  u'/organization/trulioo': (2, 300000.0),
  u'/organization/sotera-wireless': (10, 25612495.0),
  u'/organization/zannel': (3, 9999999.0),
  u'/organization/r-l': (2, 2580000.0),
  u'/organization/face-me': (1, 50000.0),
  u'/organization/glaxstar': (1, 3000000.0),
  u'/organization/smartcells': (5, 4100000.0),
  u'/organization/skaffl': (1, 18000.0),
  u'/organization/sinbads-supply-chain': (1, 100000.0),
  u'/organization/enikos': (1, 600000.0),
  u'/organization/drizly': (20, 2250000.0),
  u'/organization/adxpose': (2, 8000000.0),
  u'/organization/zoodles': (1, 2600000.0),
  u'/organization/basicgov-systems': (1, 438530.0),
  u'/organization/teraview': (5, 5500000.0),
  u'/organization/radiojar': (1, 423000.0),
  u'/organization/pelikon': (4, 9150000.0),
  u'/organization/universal-record-database': (4, 1499999.0),
  u'/organization/shanghai-

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(*zip(*list(investors_joined.values())), c = 'blue') 
plt.scatter(*zip(*list(companies_joined.values())), c = 'red') 

plt.show()


In [92]:
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn import preprocessing


n_samples = 1500
# random_state = 170 
# X, y = make_blobs(n_samples=n_samples, random_state=random_state)
X = np.transpose(np.array(zip(*list(investors_joined.values()))))
X_scaled = preprocessing.scale(X)
# Incorrect number of clusters
Kobj = KMeans(n_clusters=3)
y_pred = Kobj.fit_predict(X_scaled)
print Kobj.cluster_centers_

plt.ylabel('Total Amount Investments / $')
plt.xlabel('Total No. of Investments')
plt.scatter(X[:, 0], X[:, 1], c=y_pred)
plt.title("Investor K-means cluster")
# plt.show()

[[  2.50028002   2.13178278]
 [ 10.42317786  11.83735432]
 [ -0.1151988   -0.10854313]]


In [75]:
# counts = {}
# for x in list(KMeans(n_clusters=3, random_state=random_state).fit_predict(X_scaled)):
#     if x in 
#     print x
import numpy as np
array = KMeans(n_clusters=3).fit_predict(X_scaled)
hist = np.bincount(array)
# ii = np.nonzero(y)[0]
print hist

# for c in companies_joined:
#     co

[14003    50   442]


In [88]:
n_samples = 1500
# random_state = 170 
# X, y = make_blobs(n_samples=n_samples, random_state=random_state)
X = np.transpose(np.array(zip(*list(companies_joined.values()))))
X_scaled = preprocessing.scale(X)
# Incorrect number of clusters
# X ,y= make_blobs(n_samples=n_samples, random_state=random_state)
Kobj = KMeans(n_clusters=3)
y_pred = Kobj.fit_predict(X_scaled)
print Kobj.cluster_centers_

# plt.subplot(221)
plt.ylabel('Total Amount Investments / $')
plt.xlabel('Total No. of Investments')
plt.scatter(X[:, 0], X[:, 1], c=y_pred)
plt.title("Companies K-means cluster")
# plt.show()

[[ -0.3342758   -0.10055767]
 [  1.81349133   0.32760139]
 [  1.27240821  14.34439157]]


In [152]:
import numpy as np
n_samples = 1500
X1 = np.transpose(np.array(zip(*list(companies_joined.values()))))
X1_scaled = preprocessing.scale(X1)

# array = KMeans(n_clusters=3).fit_predict(X_scaled)

Kobj1 = KMeans(n_clusters=3, init = 'random')
array1 = Kobj1.fit_predict(X1_scaled)

plt.ylabel('Total Amount Investments / $')
plt.xlabel('Total No. of Investments')
plt.scatter(X1[:, 0], X1[:, 1], c=array1)
plt.title("Companies K-means cluster")

print Kobj1.cluster_centers_

for k in Kobj1.cluster_centers_:
    print np.linalg.norm(k)

hist1 = np.bincount(array1)
print " "
print hist1

companies_joined_class = {} 
postGdick = postG.in_degree()
count = 0
for item in companies_joined.items():
    key = item[0]
    v = companies_joined[key]
    prev_edges = v[0]
#     c = array 
    v = v[0],v[1],array1[count]
    companies_joined_class[key] = v
    count += 1
plt.show()
# companies_joined_class

[[  0.94802068  11.25512118]
 [  1.83188597   0.27193888]
 [ -0.33308028  -0.10079985]]
11.2949765787
1.85196030671
0.34799868427
 
[   78  3029 16881]


In [ ]:
import numpy as np
n_samples = 1500
X2 = np.transpose(np.array(zip(*list(investors_joined.values()))))
X2_scaled = preprocessing.scale(X2)

# array = KMeans(n_clusters=3).fit_predict(X_scaled)
Kobj2 = KMeans(n_clusters=3, init = 'random')
array2 = Kobj2.fit_predict(X2_scaled)

plt.ylabel('Total Amount Investments / $')
plt.xlabel('Total No. of Investments')
plt.scatter(X2[:, 0], X2[:, 1], c=array2)
plt.title("Companies K-means cluster")


print Kobj2.cluster_centers_
for k in Kobj2.cluster_centers_:
    print np.linalg.norm(k)
    
hist2 = np.bincount(array2)

print " "
print hist2

investors_joined_class = {} 
postGdick = postG.in_degree()
count = 0
for item in investors_joined.items():
    
    key = item[0]
    v = investors_joined[key]
    prev_edges = v[0]
    v = v[0],v[1],array2[count]
    investors_joined_class[key] = v
    count += 1
plt.show()
print "f"
# investors_joined_class

In [134]:
companies_joined_class['/organization/uber'], investors_joined_class['/organization/fidelity-investments'], investors_joined_class['/organization/start-up-chile']

((29, 209213253.0, 1), (7, 201916665.0, 1), (580, 28959662.0, 2))

In [143]:
concat_dict['/organization/']

KeyError: '/organization/esther-dyson'

In [138]:
# /organization/sequoia-capital
concat_dict = companies_joined_class.copy()
concat_dict.update(investors_joined_class)
# preG


for key in concat_dict:
    concat_dict[key] = concat_dict[key][2]
# concat_dict
import cPickle as pickle

with open('preG_cluster_dick.pickle', 'wb') as handle:
    pickle.dump(concat_dict, handle)
nx.set_node_attributes(preG, 'cluster', concat_dict)
concat_dict

# writeEdgelist(preG, "graph_with_clusters.edgelist")

{u'/organization/rsj-private-equity': 0,
 u'/organization/petra-partners': 0,
 u'/organization/ivycap-ventures': 0,
 u'/organization/sotera-wireless': 1,
 u'/organization/marketo': 0,
 u'/person/ali-partovi': 0,
 u'/person/emilios-markou': 0,
 u'/organization/skaffl': 0,
 u'/organization/idea-ventura': 0,
 u'/organization/enikos': 0,
 u'/organization/drizly': 1,
 u'/organization/basicgov-systems': 0,
 u'/organization/beamonte-investments': 0,
 u'/organization/telesoft-partners': 0,
 u'/organization/inventures': 0,
 u'/organization/clear-story': 0,
 u'/organization/bluecrest-capital-finance': 0,
 u'/organization/forticom': 0,
 u'/organization/shanghai-4space-culture-media': 0,
 u'/person/eddy-chan': 0,
 u'/organization/opti-source': 0,
 u'/person/avid-larizadeh': 0,
 u'/organization/standoutjobs': 1,
 u'/organization/cedexis': 0,
 u'/organization/svb-india-capital-partners': 0,
 u'/organization/partner-ventures': 0,
 u'/organization/centralway': 0,
 u'/organization/peerapp': 0,
 u'/orga

In [140]:
# preG.nodes(weight = 'weight')
color=nx.get_node_attributes(preG,'cluster')
color
nx.write_gpickle(preG, 'preG_pickle_cluster.gpickle')

In [120]:
from sklearn import datasets, linear_model

# Load the diabetes dataset
diabetes = datasets.load_diabetes()

X = np.transpose(np.array(zip(*list(companies_joined.values()))))
X_scaled = preprocessing.scale(X)

# Use only one feature
diabetes_X = diabetes.data[:, np.newaxis, 2]

# Split the data into training/testing sets
diabetes_X_train = X_scaled[:-20]
diabetes_X_test = X_scaled[-20:]

# Split the targets into training/testing sets
diabetes_y_train = diabetes.target[:-20]
diabetes_y_test = diabetes.target[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean square error
print("Residual sum of squares: %.2f"
      % np.mean((regr.predict(diabetes_X_test) - diabetes_y_test) ** 2))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % regr.score(diabetes_X_test, diabetes_y_test))

# Plot outputs
plt.scatter(diabetes_X_test, diabetes_y_test,  color='black')
plt.plot(diabetes_X_test, regr.predict(diabetes_X_test), color='blue',
         linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

('Coefficients: \n', array([ 938.23786125]))
Residual sum of squares: 2548.07
Variance score: 0.47


In [122]:
diabetes_X_train.shape

(422, 1)

In [123]:
diabetes_y_train.shape

(422,)

In [124]:
X_scaled

array([[ 1.22592118, -0.01377967],
       [ 2.18222582, -0.12573092],
       [ 2.18222582, -0.24876798],
       ..., 
       [ 1.22592118, -0.04327872],
       [-0.36791989, -0.25389454],
       [ 0.58838475,  0.5330317 ]])

In [130]:
y_test = np.array([x[2] for x in companies_joined_diff.values()])